### ISSUE TITLE
”通过 Docker Compose 构建 EMQX 集群“ 的Compose文件中healthcheck部分test语句错误

### ISSUE THREAD

**Issue by xiaoxx970** [emqtt/emq-docs-cn#2778]
File: [/zh_CN/deploy/install-docker.md](https://docs.emqx.com/zh/emqx/v5.1/deploy/install-docker.html)

[通过 Docker Compose 构建 EMQX 集群](https://docs.emqx.com/zh/emqx/v5.1/deploy/install-docker.html#%E9%80%9A%E8%BF%87-docker-compose-%E6%9E%84%E5%BB%BA-emqx-%E9%9B%86%E7%BE%A4) 的Compose文件中`healthcheck`部分, test应该是`["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]`, 否则报错不存在‘/opt/emqx/bin/emqx ctl’这个文件或路径

当前的内容

```yaml
healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
```
