### ISSUE TITLE
plugin auth-mnesia depends on emqx_auth_username

### ISSUE THREAD

**Issue by qzhuyan** [emqtt/emq-docs-cn#795]
File: [/en_US/advanced/auth-mnesia.md](https://docs.emqx.io/en/broker/v4.2/advanced/auth-mnesia.html)

User reports `emqx_auth_mnesia` plugin not working when the plugin `emqx_auth_username` is not enabled.
This page should describe `emqx_auth_mnesia` depends on `emqx_auth_username` and both of them should be enabled in the Plugins page.

**Comment by zmstone** [comment]
Which version ？

**Comment by qzhuyan** [comment]
4.2.0 https://emqx.slack.com/archives/CBUF2TTB8/p1623427232034200

**Comment by jjauzion** [comment]
to be more specific it’s the mnesia HTTP API that doesn’t work:
```
POST api/v4/auth_user
{
    "login": "emqx_c",
    "password": "emqx_p",
    "is_superuser": false
}
```
got `404: not_found`
but when activating  emqx_auth_username I can use:
```
POST api/v4/auth_username
{
    "username": "emqx_u",
    "password": "emqx_p"
}
```
and I’m just seeing that it’s actually not the same endpoint so I guess I didn’t fix mnesia endpoints but I’m just using another solution than mnesia ? If so then I don't understand why mnesia endpoints are not working

Here is my docker-compose if you wanna try:
```
  emqx1:
    image: emqx/emqx:4.2.0
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.io
      - EMQX_NODE__NAME=emqx.local.node
      - EMQX_RETAINER__STORAGE_TYPE=disc
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_retainer,emqx_dashboard,emqx_auth_username,emqx_auth_mnesia"
      - EMQX_AUTH__MNESIA__PASSWORD_HASH=sha256
      - EMQX_AUTH__MNESIA__1__LOGIN=bootstrap
      - EMQX_AUTH__MNESIA__1__PASSWORD=public
      - EMQX_AUTH__MNESIA__1__IS_SUPERUSER=true
      - EMQX_ALLOW_ANONYMOUS=false
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-etc:/opt/emqx/etc
      - emqx-log:/opt/emqx/log
    ports:
      - 18083:18083
      - "${GW_EMQX_PORT:?err}:${GW_EMQX_PORT:?err}"
      - "${GW_EMQX_API_PORT:?err}:${GW_EMQX_API_PORT:?err}"
    networks:
      gateway-api:
        aliases:
        - node1.emqx.io
```
